swagger: '2.0'


schemes:
  - http
  - https

host: localhost:8085
basePath: /bytebank-spi/v1

info:
  version: 1.0.0
  title: ByteBank Api
  description: Administra a movimentação bancária do correntista
    e controla o acesso através de cpf e senha
  termsOfService: http://localhost:8086/bytebank-spi/v1/termo-uso
  contact:
    name: Suporte
    url: http://localhost:8086/bytebank-spi/v1/suporte
    email: suporte@bytebankapi.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT


paths:
  '/cliente':
    post:
      summary: Cadastra Cliente
      description: Cadastra um novo cliente
      consumes:
      - application/json
      produces:
      - application/json
      operationId: cadastraCliente
      parameters:
        - in: body
          name: cliente_
          schema:
            $ref: '#/definitions/Cliente'
            
                
      responses:
        201:
          description: Cadastro efetuado com sucesso
          schema:
            $ref: '#/definitions/Cliente'
        400:
          description: Requisição inválida
        500:
          description: Erro interno no servidor

definitions:
  
  Cliente:
    type: object
    properties:
      id: 
        type: integer
        format: int64
        example: 1
      titular:
        type: string
        example: Janete Silva
      cpf:
        type: string
        maxLength: 11
        minLength: 11
        example: 12345678900
      senha:
        type: string
        format: password
        example: senha123
      conta:
        type: array
        items:
          $ref: '#/definitions/Conta'
  
  Conta:
    type: object
    properties:
      agencia:
        type: integer
        format: int32
        example: 975
      numero:
        type: integer
        format: int64
        example: 784563
      digito:
        type: integer
        format: int32
        example: 7
      saldo:
        type: number
        format: double
        example: 2567.89
      cliente:
        $ref: '#/definitions/Cliente'
        
      
        

  
  
  
  
  
  
    